sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: arAMgCfLX/hsYA3JtOKFiyEJWQICJDuthQ21rJYpJGqAlTbYNXPbRX51JM/Weuv4V2ex9ZasubTn8dG2HsON5mB7OQRmsK5RuwrAP+w8ccGWls8M+9bKjV9oItHtsX6Gshng6LvzbiVkh6Nv5RbvVxE2sweFOPLXIu/5xuMHXNSuBYImS03uBeYb7J7U4oFa0iqT3WO2TFHtFYaoix9boJ7NdJvvxt9T52aTv0YoCwb40pNu9SvgpKVgMM/fvRo30KL2wIlNORNEDD1jmf0mK2emtBk8ULeTuVbEUaOlPgLewy2XitJXOeUd+2PEn+kMMv8OAg+A2BbjSysqUa3ESdQO6wDzOIoQqDo9gvqdLnASxGAwXgbFL0WrwIAlAj0MH04bcqJScBgFeGYZmPQG2zKA1C3v7y5sp/OU2SFmHsx6Tw+zXh/6uVzyyQmlOuChD+mZGaAigP+q5dywY1oMPI0ugbacob3C0mpsY/GkCvhFl/QkNJHH/fD0FVx5LSSrRF6wg+qrOjHmEuw8Ez0slUc295ew8iwiNlXQm3LJl/1NHDMtHGH8GGtjsU2Ybkp7SEX5LmlidWDn2n5cRCM5OGTxpdc5mU2SXR6rGXRQgMFwQFGWReDJedajQ3qPma+G0fB/+93RAc7KTOoW/6VUNXG2hdTlV5gmU6Rymc5KNG8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Beauchamp-s-Career-Volume-6_4458
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy